### ISSUE TITLE
Error response from daemon: Could not find the file /fitnesse in container

### ISSUE THREAD

**Issue by maulikprajapati** [fhoeben/hsac-fitnesse-docker#3]
I recently upgraded the image from hasc fitnesse-fixtures-test-jre8-chrome-with-pdf to fitnesse-fixtures-test-jre11-chrome-with-pdf. After the upgrade, I encountered the following error while copying tests:

```
echo "Copying tests"
  docker cp ${DIR}/wiki/FitNesseRoot ${CONTAINER}:/fitnesse/wiki/
```

```
Error response from daemon: Could not find the file /fitnesse in container
```

**Configuration:**
```
fitnesse-suite8:
  image: ${FITNESSE_IMAGE}
  command: -DreRunSuiteLocation=/fitnesse/target/suite8 -DfitnesseSuiteToRun=MyTests -DTENANT=fitnesse-suite8 -DTENANTDISPLAY=Fitnesse-suite8 -DsuiteFilter=Suite8 -DexcludeSuiteFilter=Suite1,Suite2,Suite3,Suite4,Suite5,Suite6,Suite7,Suite9,
  environment:
    LANG_WHERE: NL
    ENCODING: UTF-8
    LANGUAGE: nl_NL.UTF-8
    LANG: nl_NL.UTF-8
    FITNESSE_OPTS: -DseleniumBrowser=chrome -DseleniumGridUrl=http://localhost:4444/wd/hub -Xmx300m -Xms192m
  mem_limit: 2100m
  volumes:
  - /dev/shm:/dev/shm
  networks:
    - my_network

```
